### ISSUE TITLE
Support userland applications

### ISSUE THREAD

**Issue by 0x192** [0x192/Universal-Android-Debloater#365]
As of `v0.5.x`, UAD only manages system applications (installed in the `/system` partition). You cannot see user applications (installed in `/data` partition). I create this issue to officially add this feature in the roadmap. 

It is always better to have userland bloatware apps than system bloatware apps. As you know, uninstalling an userland app remove it completely from the phone. It will not appear in `adb shell pm packages -u` and you can't restore it with ADB the same way as with a system app (which still reside in `/system` after uninstall). In practice, it's not a big deal because user apps are available in the PlayStore (or any other appstore) 

## TODO

- [ ] Use `adb shell pm packages` instead of `adb shell pm packages -s`
- [ ] Differentiate system apps from userland apps
   - [ ] In the UI  
   - [ ] Check the adb command used to uninstall them
